---
apiVersion: v2
name: workspace-system
description: A Helm chart for KloudKIT Workspace cluster-wide system management
version: 0.1.0
home: https://ws.kloudkit.com
sources:
  - https://github.com/kloudkit/ws-helm
  - https://github.com/kloudkit/ws-meta
keywords:
  - workspace
  - development-environment
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.0
