---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=300
      - id: check-json
      - id: check-yaml
        exclude: ^src/templates
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-metaschema
        files: ^src/values\.schema\.json$

  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint
        entry: >-
          bash -c
          'helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts --force-update
          && helm dependency build src/
          && helm lint src/'
        language: system
        files: ^src/
        pass_filenames: false
