---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=300
      - id: check-json
      - id: check-yaml
        exclude: ^charts/[^/]+/templates
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-metaschema
        files: ^charts/[^/]+/values\.schema\.json$

  - repo: local
    hooks:
      - id: helm-lint-workspace
        name: helm lint (workspace)
        entry: shared/scripts/helm-lint-with-deps.sh charts/workspace
        language: script
        files: ^charts/workspace
        pass_filenames: false

      - id: helm-lint-workspace-project
        name: helm lint (workspace-project)
        entry: helm lint charts/workspace-project
        language: system
        files: ^charts/workspace-project
        pass_filenames: false

      - id: helm-lint-workspace-system
        name: helm lint (workspace-system)
        entry: shared/scripts/helm-lint-with-deps.sh charts/workspace-system
        language: script
        files: ^charts/workspace-system
        pass_filenames: false
