---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=300
      - id: check-json
      - id: check-yaml
        exclude: ^charts/[^/]+/templates
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-metaschema
        files: ^charts/[^/]+/values\.schema\.json$

  - repo: local
    hooks:
      - id: helm-lint-workspace
        name: helm lint (workspace)
        entry: >-
          bash -c
          'helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts --force-update
          && helm dependency build charts/workspace
          && helm lint charts/workspace'
        language: system
        files: ^charts/workspace
        pass_filenames: false

      - id: helm-lint-ws-project
        name: helm lint (ws-project)
        entry: helm lint charts/ws-project
        language: system
        files: ^charts/ws-project
        pass_filenames: false
