{{- if (dig "scripts" "enabled" false (.Values.project | default dict)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ws-project.name" . }}-scripts
  namespace: {{ include "ws-project.namespace" . }}
data:
  {{- dig "scripts" "scripts" dict (.Values.project | default dict) | toYaml | nindent 2 }}
{{- end }}
