{{- if (dig "env" "enabled" false (.Values.project | default dict)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workspace-project.name" . }}-env
  namespace: {{ include "workspace-project.namespace" . }}
data:
  {{- toYaml (dig "env" "data" dict (.Values.project | default dict)) | nindent 2 }}
{{- end }}
