{{- if (dig "quota" "enabled" false (.Values.project | default dict)) }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "workspace-project.name" . }}
  namespace: {{ include "workspace-project.namespace" . }}
spec:
  hard:
    {{- toYaml (dig "quota" "hard" dict (.Values.project | default dict)) | nindent 4 }}
{{- end }}
