{{- if (dig "secret" "enabled" false (.Values.project | default dict)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workspace-project.name" . }}
  namespace: {{ include "workspace-project.namespace" . }}
stringData:
  {{- toYaml (dig "secret" "data" dict (.Values.project | default dict)) | nindent 2 }}
{{- end }}
